import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs';
import path from 'path';

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    {
      name: 'save-profile-middleware',
      configureServer(server) {
        server.middlewares.use('/save-profile', (req, res, next) => {
          if (req.method === 'POST') {
            let body = '';
            req.on('data', chunk => {
              body += chunk.toString();
            });
            req.on('end', () => {
              try {
                const data = JSON.parse(body);
                // Sanitize filename
                const safeName = data.name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
                const filename = `${safeName}.json`;

                // Target directory: src/assets/profiles
                const targetDir = path.resolve(__dirname, 'src/assets/profiles');

                if (!fs.existsSync(targetDir)) {
                  fs.mkdirSync(targetDir, { recursive: true });
                }

                const filePath = path.join(targetDir, filename);

                // Add ID if missing or ensure it matches filename logic if needed, 
                // but usually the ID is generated by frontend.
                // We just write what we get.

                fs.writeFileSync(filePath, JSON.stringify(data, null, 2));

                res.setHeader('Content-Type', 'application/json');
                res.end(JSON.stringify({ success: true, filename }));
                console.log(`[Vite Middleware] Saved profile to ${filePath}`);
              } catch (e) {
                console.error('[Vite Middleware] Error saving profile:', e);
                res.statusCode = 500;
                res.end(JSON.stringify({ error: e.message }));
              }
            });
          } else {
            next();
          }
        });
      }
    }
  ],
})
